par(mfcol=c(2,2),mar=c(4,4,2,2))
plot(hs$datetime,hs$Global_active_power,ylab="Global Active Power(kilowatts)",xlab="",type="l")
plot(hs$datetime,hs$Sub_metering_1,type="l",col="black",xlab="",ylab="")
lines(hs$datetime,hs$Sub_metering_2,col="red")
lines(hs$datetime,hs$Sub_metering_3,col="blue")
title(xlab="",ylab="Energy sub metering")
legend("topright",lty="solid",col=c("black","Red","Blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),pt.cex = 0.5,cex=0.5)
plot(hs$datetime,hs$Voltage,type="l",xlab="datetime",ylab="voltage")
plot(hs$datetime,hs$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
